FROM node:20 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install   # Use npm install if lock file mismatch
COPY . ./
RUN npm run build

# Use nginx to serve the build
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
